export const GET_ALL_PRODUCTS_START='GET_ALL_PRODUCTS__START';
export const GET_ALL_PRODUCTS_SUCCESS='GET_ALL_PRODUCTS__SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS__FAILURE';


export const ADD_PRODUCT_TO_BASKET_START = "ADD_PRODUCT_TO_BASKET_START";
export const ADD_PRODUCT_TO_BASKET_SUCCESS = "ADD_PRODUCT_TO_BASKET_SUCCESS";
export const ADD_PRODUCT_TO_BASKET_FAILURE = "ADD_PRODUCT_TO_BASKET_FAILURE";

export const FETCH_PRODUCTS_FROM_BASKET_START='FETCH_PRODUCTS_FROM_BASKET_START';
export const FETCH_PRODUCTS_FROM_BASKET_SUCCESS='FETCH_PRODUCTS_FROM_BASKET_SUCCESS';
export const FETCH_PRODUCTS_FROM_BASKET_FAILURE='FETCH_PRODUCTS_FROM_BASKET_FAILURE';

export const DELETE_PRODUCT_FROM_BASKET_START = 'DELETE_PRODUCT_FROM_BASKET_START';
export const DELETE_PRODUCT_FROM_BASKET_SUCCESS = 'DELETE_PRODUCT_FROM_BASKET_SUCCESS';
export const DELETE_PRODUCT_FROM_BASKET_FAILURE = 'DELETE_PRODUCT_FROM_BASKET_FAILURE';