export const GET_PRODUCTS_BY_CATEGORY_START='GET_PRODUCTS_BY_CATEGORY_START';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS='GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE = 'GET_PRODUCTS_BY_CATEGORY_FAILURE';


export const GET_ALL_CATEGORIES_START = 'GET_ALL_PRODUCTS__FAILURE';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';



export const ADD_PRODUCT_TO_BASKET_SUCCESS = "ADD_PRODUCT_TO_BASKET_SUCCESS";
export const DELETE_PRODUCT_FROM_BASKET_SUCCESS = 'DELETE_PRODUCT_FROM_BASKET_SUCCESS';
