export const GET_ALL_PRODUCTS_START='GET_ALL_PRODUCTS__START';
export const GET_ALL_PRODUCTS_SUCCESS='GET_ALL_PRODUCTS__SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS__FAILURE';

export const ADD_PRODUCT_TO_BASKET_SUCCESS = "ADD_PRODUCT_TO_BASKET_SUCCESS";
export const DELETE_PRODUCT_FROM_BASKET_SUCCESS = 'DELETE_PRODUCT_FROM_BASKET_SUCCESS';
